name: Workflow 1
on: push
jobs: 
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Copying files
        uses: actions/checkout@v7
      - name: Hello world
        run: |
         echo "first github ACTion"
         echo "hello"
         ls
         cat dockerfile