name: Workflow 1
on: push
jobs: 
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello world
        run: echo "first github ACTion"
      - name: Hello world
        run: echo "hello"
      - name: Listing files
        run: ls
      - name: read dockerfile
        run: cat dockerfile